name: Snapshot Publish
on: [pull_request]

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish plugin to gradle plugins portal
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 12
        uses: actions/setup-java@v1
        with:
          java-version: 12
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Publish plugins with gradle
        run: ./gradlew publishPlugins -Pgradle.publish.key=${{secret.GRADLE_PUBLISH_KEY}} -Pgradle.publish.secret=${{secret.GRADLE_PUBLISH_SECRET}}
